export const COMMENT_ON_POST_REQUEST = "COMMENT_ON_POST_REQUEST";
export const COMMENT_ON_POST_SUCCESS = "COMMENT_ON_POST_SUCCESS";
export const COMMENT_ON_POST_FAIL = "COMMENT_ON_POST_FAIL";

export const UPDATE_COMMENT_REQUEST = "UPDATE_COMMENT_REQUEST";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL";

export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const GET_SINGLE_COMMENT_REQUEST = "GET_SINGLE_COMMENT_REQUEST";
export const GET_SINGLE_COMMENT_SUCCESS = "GET_SINGLE_COMMENT_SUCCESS";
export const GET_SINGLE_COMMENT_FAIL = "GET_SINGLE_COMMENT_FAIL";

export const REPLY_COMMENT_REQUEST = "REPLY_COMMENT_REQUEST";
export const REPLY_COMMENT_SUCCESS = "REPLY_COMMENT_SUCCESS";
export const REPLY_COMMENT_FAIL = "REPLY_COMMENT_FAIL";
