export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const GET_SINGLE_POST_REQUEST = "GET_SINGLE_POST_REQUEST";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
export const GET_SINGLE_POST_FAIL = "GET_SINGLE_POST_FAIL";

export const MY_OWN_POSTS_REQUEST = "MY_OWN_POSTS_REQUEST";
export const MY_OWN_POSTS_SUCCESS = "MY_OWN_POSTS_SUCCESS";
export const MY_OWN_POSTS_FAIL = "MY_OWN_POSTS_FAIL";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";

export const UPLOAD_IMAGE_FROM_POST_REQUEST = "UPLOAD_IMAGE_FROM_POST_REQUEST";
export const UPLOAD_IMAGE_FROM_POST_SUCCESS = "UPLOAD_IMAGE_FROM_POST_SUCCESS";
export const UPLOAD_IMAGE_FROM_POST_FAIL = "UPLOAD_IMAGE_FROM_POST_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const POST_LIKE_REQUEST = "POST_LIKE_REQUEST";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const POST_LIKE_FAIL = "POST_LIKE_FAIL";

export const POST_DISLIKE_REQUEST = "POST_DISLIKE_REQUEST";
export const POST_DISLIKE_SUCCESS = "POST_DISLIKE_SUCCESS";
export const POST_DISLIKE_FAIL = "POST_DISLIKE_FAIL";

export const GET_LIKEDISLIKE_REQUEST = "GET_LIKEDISLIKE_REQUEST";
export const GET_LIKEDISLIKE_SUCCESS = "GET_LIKEDISLIKE_SUCCESS";
export const GET_LIKEDISLIKE_FAIL = "GET_LIKEDISLIKE_FAIL";
