export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const UPDATE_USER_PROFILEPICTURE_REQUEST =
  "UPDATE_USER_PROFILEPICTURE_REQUEST";
export const UPDATE_USER_PROFILEPICTURE_SUCCESS =
  "UPDATE_USER_PROFILEPICTURE_SUCCESS";
export const UPDATE_USER_PROFILEPICTURE_FAIL =
  "UPDATE_USER_PROFILEPICTURE_FAIL";
